92 change navbar text color according to url
skku-comit/comit-website pull request #95
Opened 2024-08-03 22:33 UTC by manamana32321

### Description
![image](https://github.com/user-attachments/assets/84498f89-2290-4044-8af7-adc3b36a3c0d)
`NavLink`만 client component로 전환하고
`const pathname = usePathname()`에 따라 텍스트 색을 변경합니다.
Closes #92 

### Additional context
#93 을 해결하려고 시도했지만 `layout.tsx`의 구성으로 인해 스크롤을 내려도 window, document, document.body, main 등 주요 요소들의 스크롤 값이 0으로 고정됩니다.
아마 이런 구성을 사용한 이유는 `components/main/Main.tsx`의 다양한 애니메이션을 구현하기 위함으로 추측됩니다.(@B0XERCAT)
따라서 애니메이션 구현 방식과 스크롤바 숨김 처리 방식에 대한 논의가 필요합니다.

2024-08-05 08:25 UTC, jihostudy commented
#93 관련 이유 확인 결과 body 태그에 적용된 scroll이 적용되려면 scroll된 영역이 존재해야 합니다.

계속 0으로 나타나는 이유는 현재 scroll이 되지 않은 상태입니다. 그저 세로로 긴 영역을 보여주기 위해 scroll된것처럼 보일 뿐입니다.

해결방법은 제가 pr로 올리겠습니다.

2024-08-05 09:09 UTC, jihostudy requested changes

2024-08-05 12:46 UTC, manamana32321 commented on components/common/Header/index.tsx
> +          <NavLink href="/clubroom" isDarkMode={isDarkMode} text="Clubroom" />
완료했습니다!

2024-08-05 12:49 UTC, manamana32321 commented on components/common/ScrollToTopButton.tsx
> +import React from 'react'
react hook만 브라우저 API에 해당되는 줄 알았네요.
plain javascript의 dom api도 이에 해당되군요
한 수 배웁니다!

2024-08-05 14:30 UTC, jihostudy requested changes

2024-08-05 14:30 UTC, jihostudy commented on constants/routes.ts
> +
잘 정리해주셨습니다!

한가지 아쉬운 점은 satisfies Route를 계속 반복해줘야 한다는 것인데요, 이에 대해 export const ROUTES: { [key: string]: Route } 처럼 들어갈 수 있는 객체 형식을 지정해주는 건 어떨까요?

2024-08-05 14:30 UTC, jihostudy commented on components/common/ScrollToTopButton.tsx
> +    console.log(window)
콘솔로그는 test후 삭제해주시는 습관 들여주시면 좋아요!

2024-08-05 14:31 UTC, jihostudy commented
해당 사항들 수정 후 병합하셔도 되겠습니다 :)

2024-08-06 05:56 UTC, manamana32321 commented on components/common/ScrollToTopButton.tsx
> +    console.log(window)
좋습니다 :)

2024-08-06 05:57 UTC, manamana32321 commented on constants/routes.ts
> +
아주 좋은 방법이네요!
하나 알아갑니다

2024-08-06 06:50 UTC, jihostudy approved these changes
수고하셨습니다!

2024-08-06 06:54 UTC, merged